sample_file: /cluster/home/selghamr/workflows/intialize/ExomeSeq/config/samples.tsv
bed_file: /cluster/home/selghamr/workflows/intialize/ExomeSeq/config/hg38_bed.tsv
indel_vcf: /cluster/home/selghamr/workflows/intialize/ExomeSeq/config/indels.tsv
snv_vcf: /cluster/home/selghamr/workflows/intialize/ExomeSeq/config/snvs.tsv

intersects:
    snv:
        0001: +1
        0002: +2
        0003: +3
    indel:
        0001: +1
        0002: +2
